### PR TITLE
Functional programming session draft

### PR DESCRIPTION
**Pull request by lwjohnst86**
Start of Feb 28th session.

### CODE REVIEW

**Comment by lwjohnst86** [comment]
Hey @privefl, I've finished modified the content and developed two exercises. I cut some sections because based on experience there was too much content for a 1.25 hour session (we still may run over time a bit with this content). I rearranged some of the sections to better fit with the exercises. Let me know what you think.

See you tomorrow at the AU library room! I'll be there probably around 12:50 to setup.

**Comment by privefl** [comment]
I made minor changes.
Can we see now how it is rendered on the website? :-)

**Comment by lwjohnst86** [comment]
Looks great! Thanks :)

**Comment by lwjohnst86** [comment]
Should be live at https://au-cru.github.io/site/material/2020-02-28-fp-purrr/ in about 1-2 min :)

**Comment by privefl** [comment]
Add this link: https://stackoverflow.com/questions/45101045/why-use-purrrmap-instead-of-lapply

**Pull request merged**
